'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace ndfdSOAPserver

    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ndfdXMLBinding", [Namespace]:="http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl")> _
    Public Class ndfdXML
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Protected Overrides Function GetWebRequest(ByVal uri As Uri) As System.Net.WebRequest
            Dim webRequest As System.Net.HttpWebRequest = MyBase.GetWebRequest(uri)
            webRequest.KeepAlive = False
            Return webRequest
        End Function

        '<remarks/>
        Public Sub New()
            MyBase.New()
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("NDFD_WebService.ndfdSOAPserver.ndfdXML")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://www.weather.gov/forecasts/xml/SOAP_server/ndfdXMLserver.php"
            End If
        End Sub

        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgen", RequestNamespace:="http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl", ResponseNamespace:="http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl")> _
        Public Function NDFDgen(ByVal latitude As Decimal, ByVal longitude As Decimal, ByVal product As String, ByVal startTime As Date, ByVal endTime As Date, ByVal weatherParameters As weatherParametersType) As <System.Xml.Serialization.SoapElementAttribute("dwmlOut")> String
            Dim results() As Object = Me.Invoke("NDFDgen", New Object() {latitude, longitude, product, startTime, endTime, weatherParameters})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginNDFDgen(ByVal latitude As Decimal, ByVal longitude As Decimal, ByVal product As String, ByVal startTime As Date, ByVal endTime As Date, ByVal weatherParameters As weatherParametersType, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("NDFDgen", New Object() {latitude, longitude, product, startTime, endTime, weatherParameters}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndNDFDgen(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDay", RequestNamespace:="http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl", ResponseNamespace:="http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl")> _
        Public Function NDFDgenByDay(ByVal latitude As Decimal, ByVal longitude As Decimal, <System.Xml.Serialization.SoapElementAttribute(DataType:="date")> ByVal startDate As Date, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal numDays As String, ByVal format As String) As <System.Xml.Serialization.SoapElementAttribute("dwmlByDayOut")> String
            Dim results() As Object = Me.Invoke("NDFDgenByDay", New Object() {latitude, longitude, startDate, numDays, format})
            Return CType(results(0), String)
        End Function

        '<remarks/>
        Public Function BeginNDFDgenByDay(ByVal latitude As Decimal, ByVal longitude As Decimal, ByVal startDate As Date, ByVal numDays As String, ByVal format As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("NDFDgenByDay", New Object() {latitude, longitude, startDate, numDays, format}, callback, asyncState)
        End Function

        '<remarks/>
        Public Function EndNDFDgenByDay(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function
    End Class

    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("weatherParametersType", "http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl")> _
    Public Class weatherParametersType

        '<remarks/>
        Public maxt As Boolean

        '<remarks/>
        Public mint As Boolean

        '<remarks/>
        Public temp As Boolean

        '<remarks/>
        Public dew As Boolean

        '<remarks/>
        Public pop12 As Boolean

        '<remarks/>
        Public qpf As Boolean

        '<remarks/>
        Public sky As Boolean

        '<remarks/>
        Public snow As Boolean

        '<remarks/>
        Public wspd As Boolean

        '<remarks/>
        Public wdir As Boolean

        '<remarks/>
        Public wx As Boolean

        '<remarks/>
        Public waveh As Boolean

        '<remarks/>
        Public icons As Boolean

        '<remarks/>
        Public rh As Boolean

        '<remarks/>
        Public appt As Boolean
    End Class
End Namespace